apiVersion: v1
kind: Service
metadata:
  name: knowledge-api
  namespace: {{ include "knowledge-local.namespace" . }}
  labels:
    app: knowledge-api
    {{- include "knowledge-local.labels" . | nindent 4 }}
spec:
  selector:
    app: knowledge-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      name: http
