#!/usr/bin/env python
"""TODO/FIXME/HACK/XXX 분류 스크립트 — PR-14 (L).

기능:
1. ``src/`` 전반의 TODO/FIXME/HACK/XXX 마커를 grep 으로 추출
2. age (git blame) + 카테고리(test/connector/lint/general) 분류
3. P0 (>180d, non-test) / P1 (>90d) / P2 우선순위 부여
4. ``--write`` 시 ``docs/TECH_DEBT.md`` 표 갱신
5. ``--check-delta --base origin/main`` 시 base 대비 +N 초과면 exit 1 (CI 가드)

사용:
    python scripts/ops/audit_todos.py
    python scripts/ops/audit_todos.py --write
    python scripts/ops/audit_todos.py --check-delta --base origin/main --max-delta 50
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]

TAG_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX)\b", re.IGNORECASE)


@dataclass(frozen=True)
class Item:
    path: str
    line: int
    tag: str
    text: str
    category: str
    age_days: int
    priority: str


def _git_grep(root: Path) -> list[tuple[str, int, str]]:
    """git grep -nE 결과 (path, line, raw_text).

    Note: ``-E`` (POSIX ERE) does not support ``\\b`` word boundary on most
    git builds. We use a plain alternation and rely on Python ``TAG_RE``
    in the caller to enforce word boundary semantics post-filter.
    """
    try:
        out = subprocess.check_output(
            [
                "git", "-C", str(root), "grep", "-nE",
                r"(TODO|FIXME|HACK|XXX)", "--",
                "src/", "scripts/",
            ],
            text=True,
        )
    except subprocess.CalledProcessError:
        return []
    rows: list[tuple[str, int, str]] = []
    for line in out.splitlines():
        m = re.match(r"^(.+?):(\d+):(.*)$", line)
        if not m:
            continue
        rows.append((m.group(1), int(m.group(2)), m.group(3)))
    return rows


def _classify(path: str, raw: str) -> str:
    if "noqa" in raw.lower():
        return "lint-suppressed"
    if "/connectors/" in path:
        return "connector-debt"
    if path.startswith("tests/") or "/test_" in path:
        return "test-debt"
    return "general"


def _git_blame_age_days(path: str, line: int) -> int:
    """Best-effort blame to estimate age. Returns 0 on failure."""
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "blame", "-L",
             f"{line},{line}", "--porcelain", path],
            text=True, stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return 0
    m = re.search(r"^author-time (\d+)$", out, re.MULTILINE)
    if not m:
        return 0
    ts = int(m.group(1))
    now = _dt.datetime.now(_dt.timezone.utc).timestamp()
    return max(0, int((now - ts) / 86400))


def _priority(age_days: int, category: str) -> str:
    if age_days > 180 and category != "test-debt":
        return "P0"
    if age_days > 90:
        return "P1"
    return "P2"


_SELF_PATH = "scripts/ops/audit_todos.py"


def collect(root: Path = REPO_ROOT) -> list[Item]:
    items: list[Item] = []
    for path, line, raw in _git_grep(root):
        # Skip self-matches — this script defines the regex it greps for.
        if path == _SELF_PATH:
            continue
        m = TAG_RE.search(raw)
        if not m:
            continue
        tag = m.group(1).upper()
        category = _classify(path, raw)
        age = _git_blame_age_days(path, line)
        items.append(
            Item(
                path=path, line=line, tag=tag,
                text=raw.strip()[:200],
                category=category, age_days=age,
                priority=_priority(age, category),
            )
        )
    return items


def render_markdown(items: Iterable[Item]) -> str:
    items = sorted(
        items,
        key=lambda i: ({"P0": 0, "P1": 1, "P2": 2}[i.priority], -i.age_days),
    )
    lines = [
        "# Tech Debt Audit",
        "",
        f"_Generated by ``scripts/ops/audit_todos.py`` "
        f"on {_dt.date.today().isoformat()}_",
        "",
        "| Priority | Age (d) | Category | Tag | Path:Line | Text |",
        "|---|---|---|---|---|---|",
    ]
    for it in items:
        path = it.path.replace("|", "\\|")
        text = it.text.replace("|", "\\|")[:100]
        lines.append(
            f"| {it.priority} | {it.age_days} | {it.category} | "
            f"{it.tag} | `{path}:{it.line}` | {text} |"
        )
    lines.append("")
    return "\n".join(lines)


def check_delta(base: str, max_delta: int) -> int:
    """Return current - base count. Exit code 1 if exceeded."""
    current = len(collect())
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", base],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        print(f"[audit_todos] base ref {base} not found — skipping delta check")
        return 0

    # Count via base by checking out a worktree-free pathspec grep on the ref.
    # ``-E`` lacks ``\b`` so we use plain alternation; word-boundary fidelity
    # only matters for the per-file audit, not the aggregate delta.
    try:
        bcount_text = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "grep", "-cE",
             r"(TODO|FIXME|HACK|XXX)", out, "--",
             "src/", "scripts/"],
            text=True, stderr=subprocess.DEVNULL,
        )
        base_count = sum(int(line.rsplit(":", 1)[-1])
                         for line in bcount_text.splitlines() if line.strip())
    except subprocess.CalledProcessError:
        base_count = 0

    delta = current - base_count
    print(f"TODO count: current={current} base={base_count} delta={delta:+d}")
    if delta > max_delta:
        print(
            f"FAIL: delta {delta} > max_delta {max_delta} — "
            "consider resolving old TODOs before adding new ones",
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit TODO/FIXME markers")
    parser.add_argument("--write", action="store_true",
                        help="Write docs/TECH_DEBT.md")
    parser.add_argument("--check-delta", action="store_true",
                        help="Exit 1 when count grows over base+max-delta")
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--max-delta", type=int, default=50)
    args = parser.parse_args()

    if args.check_delta:
        return check_delta(args.base, args.max_delta)

    items = collect()
    md = render_markdown(items)
    if args.write:
        out = REPO_ROOT / "docs" / "TECH_DEBT.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
        print(f"Wrote {out} — {len(items)} items")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
