"""Tests for migrate_schema_to_yaml.py — idempotency + round-trip."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from scripts.ops import migrate_schema_to_yaml as migrate


@pytest.fixture
def out_dir(tmp_path, monkeypatch):
    d = tmp_path / "graph_schemas"
    d.mkdir()
    monkeypatch.setattr(migrate, "OUT_DIR", d)
    return d


class TestMigration:
    def test_writes_all_known_kbs(self, out_dir: Path):
        migrate.main()
        files = sorted(p.name for p in out_dir.glob("*.yaml"))
        # 6 KBs from original KB_SCHEMA_PROFILES
        assert files == [
            "a-ari.yaml",
            "drp.yaml",
            "g-espa.yaml",
            "hax.yaml",
            "itops_general.yaml",
            "partnertalk.yaml",
        ]

    def test_yaml_has_required_keys(self, out_dir: Path):
        migrate.main()
        data = yaml.safe_load((out_dir / "g-espa.yaml").read_text())
        assert data["kb_id"] == "g-espa"
        assert data["version"] == 1
        assert "Store" in data["nodes"]
        assert "OPERATES" in data["relationships"]
        assert "prompt_focus" in data
        assert data["options"]["disable_bootstrap"] is False
        assert data["_metadata"]["migrated_from"].startswith("prompts.py")

    def test_idempotent_reruns(self, out_dir: Path):
        migrate.main()
        first_contents = {
            p.name: p.read_text() for p in out_dir.glob("*.yaml")
        }

        # Rerun — existing files should be left alone (not overwritten)
        migrate.main()
        second_contents = {
            p.name: p.read_text() for p in out_dir.glob("*.yaml")
        }
        assert first_contents == second_contents

    def test_roundtrip_via_resolver(self, out_dir: Path, monkeypatch):
        """YAML generated by migrate round-trips through SchemaResolver
        back to the same nodes/relationships/prompt_focus the original
        hardcoded dict defined."""
        from src.pipelines.graphrag.schema_resolver import (
            SchemaResolver,
            invalidate_cache,
        )

        # Point resolver at the tmp dir
        monkeypatch.setattr(
            "src.pipelines.graphrag.schema_resolver._SCHEMA_DIR", out_dir,
        )
        monkeypatch.setattr(
            "src.pipelines.graphrag.schema_resolver._DEFAULTS_DIR",
            out_dir / "_defaults",
        )
        (out_dir / "_defaults").mkdir(exist_ok=True)
        invalidate_cache()

        migrate.main()

        profile = SchemaResolver.resolve(kb_id="g-espa", source_type=None)
        expected = migrate.LEGACY_PROFILES["g-espa"]
        assert set(profile.nodes) == set(expected["nodes"])
        assert set(profile.relationships) == set(expected["relationships"])
        assert profile.prompt_focus == expected["prompt_focus"]
